name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upate Apt
      run: sudo apt update

    - name: Upgrade Apt
      run: sudo apt upgrade

    - name: Install CMake
      run: sudo apt install cmake git
    
    - name: Depedency Install
      run: sudo apt install xorg-dev

    - name: Pull submodules recursively
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/cmake-build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/cmake-build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/cmake-build
      run: ctest -C ${{env.BUILD_TYPE}}

